### ISSUE TITLE
styles passed as props to rebass button is not working.

### ISSUE THREAD

**Issue by Kalpana-Nagan** [rebassjs/rebass#725] opened 2019-09-16 19:12 UTC
I am trying to apply styles to styled rebass button, which has style properties as props.Please 

Scenario: 
1. If I just use "**<Button>**" (imported from rebass) , props passed into it 
   are getting applied. 
    ```
    <Button
    variant={variant}
    type={type}
    width={width}
    px={px}
    py={py}
  >
    {children}
  </Button>
```
2. But if I use  "StyledButton"(styled button) instead of just Button, props are **not** getting applied.
     
```
<StyledButton
    variant={variant}
    type={type}
    width={width}
    px={px}
    py={py}
     >
    {children}
  </StyledButton>
```

**Please Refer code below.**

****versions used :**** 
   "styled-components": "^4.3.2",
    "rebass": ### "^4.0.5"

```
import React from 'react';
import { Button } from 'rebass';
import { string, number, oneOfType, arrayOf, node, func } from 'prop-types';
import styled from 'styled-components';

const StyledButton = styled(Button)`
  cursor: pointer;
`; 

const CustomButton = ({
  children,
  type,
  variant,
  width,
  px,
  py,
}) => (
  <StyledButton
    variant={variant}
    type={type}
    width={width}
    px={px}
    py={py}
  >
    {children}
  </StyledButton>
);

CustomButton.propTypes = {
  children: node.isRequired,
  type: string,
  variant: string,
  width: oneOfType([string, number]),
  px: oneOfType([string, number]),
  py: oneOfType([string, number]),
};

CustomButton.defaultProps = {
  type: null,
  variant: 'primary',
  width: 'auto',
  py: 4,
  px: 6,
};

export default CustomButton;

```

**Comment by jxnblk** [comment] 2019-09-16 19:18
Is this a duplicate of #723?

**Comment by Kalpana-Nagan** [comment] 2019-09-16 19:23
No, its not duplicate. its different issue.

**Closed** 2019-09-16 20:34 UTC
