### ISSUE TITLE
Not being able to override styles

### ISSUE THREAD

**Issue by vigzmv** [rebassjs/rebass#679] opened 2019-08-30 08:09 UTC
For a component `<Image height={100} />`
I expect the height to be 100px.

But due to this https://github.com/rebassjs/rebass/blob/34a20ab015a37c50ef8a51f4c9b437ce7aa23338/packages/rebass/src/index.js#L69

My custom style is overridden by the default
![image](https://user-images.githubusercontent.com/14950089/64004245-7e080d80-cb2b-11e9-84b3-437d8b449781.png)

**Comment by louissm-it** [comment] 2019-08-30 21:28
You can set the `height` to `100px` through the `sx` prop:

```
<Image src="/example.png" sx={{height: 100}} />
```

Remember the jsx pragma and import:

```
/** @jsx jsx */
import { jsx } from 'theme-ui'
```

I realise this doesn't exactly resolve your issue but maybe it helps.

Cheers

**Comment by vigzmv** [comment] 2019-08-30 21:49
Thanks, I use an older version without the `sx` prop. I am able to override my styles by extending the component.

But I really think that the default styles should come before passes style props so they can be overridden easily. Unless there's a reason for it to be like this

https://github.com/rebassjs/rebass/blob/34a20ab015a37c50ef8a51f4c9b437ce7aa23338/packages/rebass/src/index.js#L66-L70

**Comment by jxnblk** [comment] 2019-09-03 15:07
> For a component <Image height={100} /> I expect the height to be 100px.

This *should* work. Can you create a reproduction of the issue you're seeing?

**Comment by jxnblk** [comment] 2019-09-03 15:09
@louissm-it FWIW, you don't need the Theme UI `jsx` to use the `sx` prop on Rebass components

**Comment by vigzmv** [comment] 2019-09-03 16:30
Thanks for checking in jxnblk.

I found out the issue is from rebass@3.2.2
I changed my version to 3.1.1 to solve this problem.

See example. https://codesandbox.io/s/awesome-turing-eqqzg

Also Verified correct behaviour on the latest version. This issue can be closed.

**Comment by louissm-it** [comment] 2019-09-04 15:02
> @louissm-it FWIW, you don't need the Theme UI `jsx` to use the `sx` prop on Rebass components

Thank you. I thought it was needed because when removing the import I get:

` 'jsx' must be in scope when using JSX  react/react-in-jsx-scope`

However, when changing the import from `'@rebass/emotion'` to `'rebass'` everything works as expected.

Thanks again👍

**Comment by jxnblk** [comment] 2019-09-04 19:10
@louissm-it If you use a pragma comment, that function will need to be in scope. When using Rebass v4, the `sx` prop works with or without the Theme UI custom create element function, but it looks like you were maybe using an older version as well

**Comment by jxnblk** [comment] 2019-09-04 19:11
@vigzmv thanks! Going to close this out since it's not an issue in the current version

**Closed by jxnblk** 2019-09-04 19:11 UTC
